export const TOGGLE_REQUEST_INDICATOR_VISIBILITY =
  'TOGGLE_REQUEST_INDICATOR_VISIBILITY';
export const ADD_REQUEST_INDICATOR = 'ADD_REQUEST_INDICATOR';
export const REMOVE_REQUEST_INDICATOR = 'REMOVE_REQUEST_INDICATOR';
